[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "synthoor"
version = "1.0.0"
dynamic = ["dependencies"]
requires-python = ">=3.8"
readme = "README.md"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
